require:
  - rubocop-performance
  - rubocop-rails
# - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubuVersion: 3.2.2
  Exclude:
    - 'db/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false